import Head from "next/head";
import styles from "@/styles/Home.module.css";
import { Search } from "@mui/icons-material";
import { useEffect, useState } from "react";
import EdpicksGrid from "@/components/EdpicksGrid";
import LatestGrid from "@/components/LatestGrid";
import { Pagination } from "@mui/material";

export default function Home({ picks }) {
  const [age, setAge] = useState("");
  const [data, setData] = useState();
  const [pages, setPages] = useState(1);

  useEffect(() => {
    const getLatest = async () => {
      var requestOptions = {
        method: "GET",
        redirect: "follow",
      };
      // Fetch data from external API
      const rawPopularM = await fetch(
        `https://api.themoviedb.org/3/movie/popular?api_key=5ccd6301393b904c4b1b8e5b00f12401&language=en-US&page=${pages}`,
        requestOptions
      );
      const data = await rawPopularM.json();
      setData(data);
    };
    getLatest();
  }, [pages]);

  const handleChange = (e, value) => {
    setPages(value);
  };
  console.log(data);
  return (
    <>
      <Head>
        <title>Stay Here Test</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <main className={styles.main}>
        <div className={styles.left}>
          <div className={styles.searchBox}>
            <p className={styles.searchTit}>Search</p>
            <Search className={styles.SearchIcon} />
            <input
              placeholder="Search..."
              className={styles.searchBar}
              type="text"
              name=""
              id=""
            />
          </div>
          <div className={styles.FilterBox}>
            <p className={styles.FilterTit}>Search</p>
            <div className={styles.GernesSelect}>
              <label htmlFor="Genres">Genre(s)</label>
              <select className={styles.genreSelector} name="genre">
                <option value="Action">Action</option>
                <option value="Comedy">Comedy</option>
                <option value="Drama">Drama</option>
              </select>
            </div>
            <div className={styles.GernesSelect}>
              <label htmlFor="Genres">Rating</label>
              <select className={styles.genreSelector} name="genre">
                <option value="5 Stars">5 Stars</option>
                <option value="7 Stars">7 Stars</option>
                <option value="9+ Stars">9+ Stars</option>
              </select>
            </div>
            <div className={styles.GernesSelect}>
              <label htmlFor="Genres">Language</label>
              <select className={styles.genreSelector} name="genre">
                <option value="English">English</option>
                <option value="French">French</option>
                <option value="Arabic">Arabic</option>
              </select>
            </div>
            <button className={styles.Apply}>Apply Filters</button>
          </div>
        </div>
        <div className={styles.right}>
          <h3 className={styles.Edit}>Editor's picks</h3>
          <EdpicksGrid picks={picks} />
          <h3 className={styles.latestMov}>Latest Movies</h3>
          <LatestGrid data={data != undefined ? data : picks} />
          <div className={styles.paginate}>
            <Pagination size="large" onChange={handleChange} count={25} />
          </div>
        </div>
      </main>
    </>
  );
}
export async function getServerSideProps() {
  var requestOptions = {
    method: "GET",
    redirect: "follow",
  };

  // Pass data to the page via props
  const topRatedM = await fetch(
    "https://api.themoviedb.org/3/movie/top_rated?api_key=5ccd6301393b904c4b1b8e5b00f12401&language=en-US&page=1",
    requestOptions
  );
  const picks = await topRatedM.json();

  // Pass data to the page via props
  return { props: { picks } };
}
